### ISSUE TITLE
manage.py cron: error: unrecognized arguments:

### ISSUE THREAD

**Issue by Belanchuk** [jsocol/django-cronjobs#11]
After upgrading the system I get this error: "manage.py cron: error: unrecognized arguments"
Before upgrade everything worked.

Python 2.7.12 (default, Jul  1 2016, 15:12:24)
pip list | grep '[dD]jango'
Django (1.10)
django-appconf (1.0.2)
django-better500s (0.2.1)
django-common-helpers (0.8.0)
django-context-logging (1.2.1)
django-cronjobs (0.2.3)
django-db-log (2.2.1)
django-db-logger (0.1.6)
django-debug-error-logging (1.0.0)
django-debug-logging (0.4)
django-debug-toolbar (1.5)
django-extensions (1.7.2)
django-log-trigger (1.0.2)
django-logging-command (1.0)
django-logging-json (1.5.3)
django-logutils (0.4.2)
django-object-log (0.7.1)
django-picklefield (0.3.2)
django-query-logger (0.1.2)
django-timelog (0.4)

**Comment by donaldr** [comment]
I'm having the same problem, did you ever figure this out?
